spring:
  datasource:
    url: jdbc:h2:mem:h2db
  flyway:
    enabled: true
    locations: db/migration
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
server:
  port: 8090
