server:
  port: 8080
management:
  endpoints:
    web:
      base-path: "/monitor"
      exposure:
        include: "metrics,health,info"
    enabled-by-default: false
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true

  info:
    env:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

info:
  app:
    author: aao
    description: use service for manipulation